name: 'Get & Cache (npm) Dependencies'
description: 'Get the dependecies (via npm) and cache them'
inputs:
  shouldCache:
    description: Flag will decide to cache or not
    required: false
    default: 'true'
    
runs:
    using: 'composite'
    steps:
      - name: Cache dependencies
        if: inputs.shouldCache
        id: cache
        uses: actions/cache@v6
        with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: input value 
        run: echo "shouldCache ${{inputs.shouldCache}}"
        shell: bash
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.shouldCache
        run: npm ci
        shell: bash